import pandas as pd

# Input dataset
data = {
    "product": [
        "Rice", "Milk", "Bread", "Eggs", "Oil",
        "Sugar", "Tea", "Coffee", "Biscuits", "Juice",
        "Rice", "Milk"
    ],
    "category": [
        "Staples", "Dairy", "Bakery", "Dairy", "Staples",
        "Staples", "Beverage", "Beverage", "Snacks", "Beverage",
        "Staples", "Dairy"
    ],
    "opening_stock": [
        120, 80, 60, 150, 50,
        100, 70, 45, 90, 65,
        140, 75
    ],
    "units_sold": [
        72, 61, 48, 125, 31,
        64, 38, 29, 52, 41,
        88, 58
    ],
    "unit_price": [
        58, 52, 45, 7, 145,
        48, 120, 310, 35, 95,
        58, 52
    ],
    "restocked": [
        40, 50, 30, 100, 20,
        30, 20, 15, 40, 25,
        60, 45
    ]
}
df = pd.DataFrame(data)

# 1. Create closing_stock column and identify lowest remaining inventory
df['closing_stock'] = df['opening_stock'] + df['restocked'] - df['units_sold']
lowest_stock_products = df.nsmallest(3, 'closing_stock')

print("--- 1. Closing Stock Analysis ---")
print(df[['product', 'category', 'opening_stock', 'restocked', 'units_sold', 'closing_stock']])
print("\nProducts with lowest remaining inventory:")
print(lowest_stock_products[['product', 'category', 'closing_stock']])
print()

# 2. Calculate revenue generated by each product and determine highest-revenue product
df['revenue'] = df['units_sold'] * df['unit_price']
highest_revenue_row = df.loc[df['revenue'].idxmax()]

print("--- 2. Revenue Analysis ---")
print(df[['product', 'category', 'units_sold', 'unit_price', 'revenue']])
print(f"\nHighest-Revenue Product: {highest_revenue_row['product']} ({highest_revenue_row['category']}) with Revenue: {highest_revenue_row['revenue']}")
print()

# 3. Calculate inventory turnover ratio (units_sold / opening_stock) and identify high turnover
df['turnover_ratio'] = df['units_sold'] / df['opening_stock']
high_turnover_threshold = 0.80
high_turnover_products = df[df['turnover_ratio'] >= high_turnover_threshold]

print("--- 3. Inventory Turnover Ratio ---")
print(df[['product', 'category', 'turnover_ratio']])
print(f"\nProducts with unusually high turnover (>= {high_turnover_threshold}):")
print(high_turnover_products[['product', 'category', 'turnover_ratio']])
print()

# 4. Compare product categories using total units sold, total revenue, and average turnover
category_summary = df.groupby('category').agg(
    total_units_sold=('units_sold', 'sum'),
    total_revenue=('revenue', 'sum'),
    avg_inventory_turnover=('turnover_ratio', 'mean')
).reset_index()

print("--- 4. Category Comparison Summary ---")
print(category_summary.to_string(index=False))
print()

# 5. Identify category requiring urgent stock-planning and justify
print("--- 5. Stock-Planning Conclusion ---")
print(
    "Conclusion: The 'Dairy' category requires the most urgent stock-planning attention.\n"
    "Justification:\n"
    "- Dairy products (specifically Eggs and Milk) exhibit exceptionally high inventory turnover ratios "
    "(e.g., Eggs at ~0.83 and Milk entries averaging ~0.77).\n"
    "- Despite high demand and strong sales volume (244 total units sold), items like Milk have comparatively "
    "low closing buffers relative to their sales velocity, risking frequent stockouts if restock frequency "
    "or volume is not optimized."
)