ticket_sales = [
    {"ticket": "Adult", "day": "Weekday", "quantity": 45, "price": 350},
    {"ticket": "Student", "day": "Weekday", "quantity": 32, "price": 200},
    {"ticket": "Child", "day": "Weekday", "quantity": 28, "price": 120},
    {"ticket": "Adult", "day": "Weekend", "quantity": 85, "price": 350},
    {"ticket": "Student", "day": "Weekend", "quantity": 54, "price": 200},
    {"ticket": "Child", "day": "Weekend", "quantity": 67, "price": 120},
    {"ticket": "Senior", "day": "Weekday", "quantity": 21, "price": 180},
    {"ticket": "Senior", "day": "Weekend", "quantity": 39, "price": 180},
    {"ticket": "Adult", "day": "Weekday", "quantity": 38, "price": 350},
    {"ticket": "Student", "day": "Weekend", "quantity": 61, "price": 200}
]

# ---------------------------------------------------------
# Task 1: Calculate total revenue generated by each record
# ---------------------------------------------------------
records_with_revenue = []
for record in ticket_sales:
    new_record = record.copy()
    new_record["total_revenue"] = record["quantity"] * record["price"]
    records_with_revenue.append(new_record)


# ---------------------------------------------------------
# Task 2: Calculate total revenue & tickets sold per type
# ---------------------------------------------------------
ticket_summary = {}
for record in records_with_revenue:
    t_type = record["ticket"]
    if t_type not in ticket_summary:
        ticket_summary[t_type] = {"total_revenue": 0, "total_tickets": 0}
    ticket_summary[t_type]["total_revenue"] += record["total_revenue"]
    ticket_summary[t_type]["total_tickets"] += record["quantity"]

# Identify the largest revenue contributor
largest_contributor = max(ticket_summary, key=lambda x: ticket_summary[x]["total_revenue"])


# ---------------------------------------------------------
# Task 3: Compare Weekday vs Weekend revenue & % increase
# ---------------------------------------------------------
weekday_revenue = sum(r["total_revenue"] for r in records_with_revenue if r["day"] == "Weekday")
weekend_revenue = sum(r["total_revenue"] for r in records_with_revenue if r["day"] == "Weekend")

percentage_increase = ((weekend_revenue - weekday_revenue) / weekday_revenue) * 100


# ---------------------------------------------------------
# Task 4: Reusable function for >25% revenue contribution
# ---------------------------------------------------------
def get_high_revenue_ticket_types(data, threshold_percentage=25.0):
    overall_revenue = sum(r["total_revenue"] for r in data)
    
    type_revenue = {}
    for r in data:
        t_type = r["ticket"]
        type_revenue[t_type] = type_revenue.get(t_type, 0) + r["total_revenue"]
        
    top_types = []
    for t_type, rev in type_revenue.items():
        percentage = (rev / overall_revenue) * 100
        if percentage > threshold_percentage:
            top_types.append(t_type)
            
    return top_types

high_contributors = get_high_revenue_ticket_types(records_with_revenue, 25.0)


# ---------------------------------------------------------
# Task 5: Recommendation for Promotional Campaign
# ---------------------------------------------------------
# Recommendation logic:
# Adult tickets provide both high sales volume and by far the largest revenue share. 
# Promoting Adult tickets maximizes overall revenue return.


# ---------------------------------------------------------
# Output Results
# ---------------------------------------------------------
print("=== TASK 1: Records with Revenue ===")
for r in records_with_revenue:
    print(r)

print("\n=== TASK 2: Summary by Ticket Type ===")
for t, metrics in ticket_summary.items():
    print(f"Ticket: {t} | Revenue: {metrics['total_revenue']} | Tickets Sold: {metrics['total_tickets']}")
print(f"-> Largest Revenue Contributor: {largest_contributor}")

print("\n=== TASK 3: Weekday vs Weekend ===")
print(f"Weekday Revenue: {weekday_revenue}")
print(f"Weekend Revenue: {weekend_revenue}")
print(f"Percentage Increase (Weekend relative to Weekday): {percentage_increase:.2f}%")

print("\n=== TASK 4: Ticket Types Contributing > 25% Revenue ===")
print(high_contributors)

print("\n=== TASK 5: Campaign Recommendation ===")
print("Recommended Ticket Type: Adult")
print("Reasoning: Adult tickets drive the highest total revenue and substantial visitor volume, making them the most effective segment for a high-impact promotional campaign.")