bookings = [
    {"guest": "A", "room": "Standard", "nights": 3, "rate": 3200},
    {"guest": "B", "room": "Deluxe", "nights": 2, "rate": 4800},
    {"guest": "C", "room": "Suite", "nights": 4, "rate": 8500},
    {"guest": "D", "room": "Standard", "nights": 5, "rate": 3200},
    {"guest": "E", "room": "Deluxe", "nights": 3, "rate": 4800},
    {"guest": "F", "room": "Suite", "nights": 2, "rate": 8500},
    {"guest": "G", "room": "Standard", "nights": 1, "rate": 3200},
    {"guest": "H", "room": "Deluxe", "nights": 6, "rate": 4800}
]

# Calculate the total booking revenue for every guest using nights × rate.
print("--- 1. Guest Revenue ---")
guest_revenues = {}
for b in bookings:
  revenue = b["nights"] * b["rate"]
  guest_revenues[b["guest"]] = revenue
  print(f"Guest {b['guest']}: Rs.{revenue}")


# Create a dictionary containing total revenue generated by each room type.
room_revenue = {}
room_counts = {}
for b in bookings:
  room = b["room"]
  rev = b["nights"] * b["rate"]
  room_revenue[room] = room_revenue.get(room, 0) + rev
  room_counts[room] = room_counts.get(room, 0) + 1

print("\n--- 2. Total Revenue by Room Type ---")
print(room_revenue)

# Identify the guest with the highest total booking value and calculate how much they spent.

highest_guest = max(guest_revenues, key=guest_revenues.get)
print("\n--- 3. Highest Spending Guest ---")
print(
    f"Guest {highest_guest} spent the most with Rs.{guest_revenues[highest_guest]}"
)

# Create a function that classifies a booking as "Short", "Medium", or "Long" for 1–2, 3–4, and 5+ nights respectively, then apply it to every booking.

def classify_stay(nights):
  if 1 <= nights <= 2:
    return "Short"
  elif 3 <= nights <= 4:
    return "Medium"
  else:
    return "Long"


print("\n--- 4. Stay Length Classifications ---")
for b in bookings:
  classification = classify_stay(b["nights"])
  print(
      f"Guest {b['guest']} ({b['room']}) - {b['nights']} nights: {classification}"
  )

# 1. Determine which room type has the highest average revenue per booking and explain what this indicates about the hotel's current booking mix.

room_avg_revenue = {
    room: room_revenue[room] / room_counts[room] for room in room_revenue
}
highest_avg_room = max(room_avg_revenue, key=room_avg_revenue.get)

print("\n--- 5. Average Revenue per Room Type ---")
for room, avg in room_avg_revenue.items():
  print(f"{room}: Rs.{avg:.2f}")
print(
    f"\nRoom type with highest average revenue per booking:"
    f" {highest_avg_room}"
)