import numpy as np

power = np.array([
    [5.2, 5.8, 6.1, 4.9, 6.5, 6.8, 5.9, 6.3],
    [4.8, 5.1, 5.6, 4.5, 5.9, 6.2, 5.4, 5.8],
    [6.1, 6.4, 6.8, 5.7, 7.0, 7.3, 6.6, 7.1],
    [3.9, 4.4, 4.1, 3.7, 4.8, 5.0, 4.3, 4.6]
])

panels = np.array(["P1", "P2", "P3", "P4"])

# Calculate the total energy generated by each panel and identify the highest-producing panel.

total_energy = power.sum(axis=1)
highest_panel = np.argmax(total_energy)
print("Total Energy by Panel:", total_energy)
print("Highest Producing Panel:", panels[highest_panel])

# Calculate the daily total energy generation and identify the day with the lowest overall production.

daily_total = power.sum(axis=0)
lowest_day = np.argmin(daily_total)
print("Daily Total Energy:", daily_total)
print("Lowest Production Day:", lowest_day)

# Calculate the coefficient of variation for each panel using standard deviation / mean × 100, and identify the least consistent panel.

panel_means = np.mean(power, axis=1)
panel_stds = np.std(power, axis=1, ddof=1)
cvs = (panel_stds / panel_means) * 100
least_consistent_idx = np.argmax(cvs)
least_consistent_panel = panels[least_consistent_idx]

print("--- 3. Coefficient of Variation (CV) ---")
for p, cv in zip(panels, cvs):
  print(f"Panel {p}: {cv:.2f}%")
print(f"Least consistent panel: {least_consistent_panel}\n")
# Create a NumPy Boolean mask for production values below 4.5 kWh and determine how many such readings each panel contains.

mask = power < 4.5
counts_below_45 = np.sum(mask, axis=1)

print("--- 4. Readings Below 4.5 kWh ---")
for p, count in zip(panels, counts_below_45):
  print(f"Panel {p}: {count} readings below 4.5 kWh")
print()

# 1. Normalise each panel's production relative to its own maximum value and identify which panel shows the largest improvement between its lowest and highest normalised production values.

# 5. Normalise each panel's production relative to its own maximum value
normalized = power / np.max(power, axis=1, keepdims=True)
min_normalized = np.min(normalized, axis=1)
improvements = 1.0 - min_normalized
largest_improvement_idx = np.argmax(improvements)
largest_improvement_panel = panels[largest_improvement_idx]

print("--- 5. Normalised Production & Improvements ---")
for p, imp in zip(panels, improvements):
  print(f"Panel {p} improvement range: {imp:.3f}")
print(f"Panel with the largest improvement: {largest_improvement_panel}")