sales = [
    {"product": "Rice", "units": 42, "price": 58},
    {"product": "Milk", "units": 65, "price": 52},
    {"product": "Bread", "units": 38, "price": 45},
    {"product": "Eggs", "units": 90, "price": 7},
    {"product": "Oil", "units": 27, "price": 145},
    {"product": "Sugar", "units": 51, "price": 48},
    {"product": "Tea", "units": 33, "price": 120},
    {"product": "Biscuits", "units": 74, "price": 35}
]

# Calculate the revenue generated by each product and store the results in a new data structure.
revenue = {}

for r in sales:
    revenue[r['product']] = (r['units'] * r['price'])

print(revenue)

# Identify the product with the highest revenue and the product with the lowest revenue.

high_rev = max(revenue.items(), key=lambda x: x[1])
low_rev = min(revenue.items(), key=lambda x: x[1])
print(high_rev)
print(low_rev)


# Calculate the total revenue and determine what percentage of total revenue comes from the top-performing product.

total_rev = sum(revenue.values())

top_product,top_rev = max(revenue.items(), key=lambda x: x[1])

top_percentage = (top_rev / total_rev) * 100

print(f"Total Revenue: {total_rev}")
print(f"Top Product: {top_product} ({top_rev})")
print(f"Percentage Contribution: {top_percentage:.2f}%")

# Create a reusable function that classifies products as "Low", "Medium", or "High" based on revenue using reasonable thresholds that you define.
def rev_classify(rev):
    classified = {}
    
    for product, rev in rev.items():
        if rev < 2000:
            category = "Low"
        elif rev <= 3500:
            category = "Medium"
        else:
            category = "High"
            
        classified[product] = {
            "revenue": rev,
            "category": category
        }
        
    return classified

result = rev_classify(revenue)

print(result)

# 1. Use your classification to determine how many products belong to each revenue category and explain what this tells the supermarket manager.

counts = {"Low": 0, "Medium": 0, "High": 0}
for rev in revenue.values():
    if rev < 2000:
        counts["Low"] += 1
    elif rev <= 3500:
        counts["Medium"] += 1
    else:
        counts["High"] += 1

print(counts)